import streamlit as st
import onnxruntime as ort
import numpy as np
import os
import sys
import time
import pandas as pd
import torch
import matplotlib.pyplot as plt
import platform
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax

# --- CONFIG IMPORT ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
try:
    import config
except ImportError:
    st.error("CRITICAL ERROR: Could not import 'config.py'. Ensure this script is in the /src folder.")
    st.stop()

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Thesis Benchmark Platform",
    layout="wide",
    page_icon="⚡"
)

# --- DARK HCI CSS ---
st.markdown("""
<style>
    .main { background-color: #0E1117; }
    .metric-card { background-color: #1E1E1E; border-radius: 12px; padding: 18px; border: 1px solid #333; margin-bottom: 10px; }
    .training-box { 
        border: 1px solid #444; border-radius: 10px; padding: 15px; background: #161b22; min-height: 180px;
        transition: all 0.5s ease;
    }
    .stage-label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 5px; font-weight: bold;}
    .active-stage { border: 2px solid #4CAF50 !important; background: #0d1a0d !important; box-shadow: 0 0 15px rgba(76, 175, 80, 0.2); }
    .completed-stage { border: 1px solid #4CAF50; opacity: 0.6; }
    .data-preview { font-family: monospace; font-size: 11px; background: #000; padding: 10px; border-radius: 5px; color: #00FF00; height: 60px; overflow-y: hidden; white-space: nowrap; text-overflow: ellipsis; }
    h1, h2, h3 { color: #e6e6e6 !important; }
    .stMetric > div { background-color: #1E1E1E !important; padding: 10px; border-radius: 5px; border: 1px solid #333; }
    .stMetric label { color: #aaaaaa !important; }
    .stMetric div[data-testid="stMetricValue"] { color: #ffffff !important; }
</style>
""", unsafe_allow_html=True)

# ----------------------------------------------------
# MODEL REGISTRY
# ----------------------------------------------------
MODELS = {
    "Model A": {"name": "Base DistilBERT", "path": config.MODEL_A_DIR, "type": "pytorch"},
    "Model B": {"name": "DAPT-DistilBERT", "path": config.MODEL_B_FINETUNED_DIR, "type": "pytorch"},
    "Model C": {"name": "XLM-RoBERTa", "path": config.MODEL_C_DIR, "type": "pytorch"},
    "Model D": {
        "name": "Optimized ONNX",
        # FIX: Point to directory (ORT finds model.onnx automatically in our standard structure)
        "path": config.MODEL_D_DIR, 
        "tokenizer": config.MODEL_D_DIR,
        "type": "onnx"
    }
}

# Path to the metrics file generated by 08_evaluate_metrics.py
RESULTS_PATH = os.path.join(config.RESULTS_DIR, "final_metrics.csv")

# ----------------------------------------------------
# RESOURCE LOADERS
# ----------------------------------------------------
@st.cache_resource
def load_one_model(key):
    """Loads a single model into memory (cached) - CPU ENFORCED."""
    try:
        model_conf = MODELS[key]
        path = model_conf["path"]
        tok_path = model_conf.get("tokenizer", model_conf["path"])
        
        # Check existence
        if not os.path.exists(path) and not os.path.exists(tok_path):
             return None, None, "error"

        # --- FIX: ROBUST TOKENIZER LOADING ---
        try:
            tokenizer = AutoTokenizer.from_pretrained(tok_path)
        except Exception:
            # Fallback for XLM-R or corrupted local json
            if "Model C" in key:
                tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
            else:
                tokenizer = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased")

        # Load Model Engine
        if model_conf["type"] == "onnx":
            options = ort.SessionOptions()
            options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
            
            # Handle Directory vs File path for ONNX
            model_file = os.path.join(path, "model.onnx") if os.path.isdir(path) else path
            
            # STRICT CPU PROVIDER
            model = ort.InferenceSession(model_file, options, providers=["CPUExecutionProvider"])
            return tokenizer, model, "onnx"
        else:
            model = AutoModelForSequenceClassification.from_pretrained(path)
            # STRICT CPU DEVICE
            model.to("cpu")
            model.eval()
            return tokenizer, model, "pytorch"
            
    except Exception as e:
        print(f"Error loading {key}: {e}")
        return None, None, "error"

@st.cache_data
def load_thesis_metrics():
    """Loads the CSV metrics generated by the evaluation script."""
    if os.path.exists(RESULTS_PATH):
        df = pd.read_csv(RESULTS_PATH)
        df.columns = [c.strip() for c in df.columns] # Clean column names
        return df
    return None

def compute_research_metrics(df):
    """Computes derived metrics like Speedup and Efficiency."""
    # Identify Baseline (Model A usually, or slowest)
    baseline = df.loc[df["Avg Latency (ms)"].idxmax()]
    
    # Calculate relative metrics
    df["Speedup_Factor"] = baseline["Avg Latency (ms)"] / df["Avg Latency (ms)"]
    
    # Normalize F1 for Retention calculation (relative to best performing model)
    best_f1 = df["Macro F1 Score"].max()
    df["Performance_Retention"] = (df["Macro F1 Score"] / best_f1) * 100
    
    # Identify Pareto Optimal points
    pareto_flags = []
    for i, row in df.iterrows():
        dominated = False
        for j, other in df.iterrows():
            if (other["Avg Latency (ms)"] <= row["Avg Latency (ms)"] and 
                other["Macro F1 Score"] >= row["Macro F1 Score"] and 
                j != i):
                dominated = True
                break
        pareto_flags.append(not dominated)
    df["Pareto_Optimal"] = pareto_flags
    
    # Standardize column names for the app
    df = df.rename(columns={
        "Avg Latency (ms)": "Latency_ms", 
        "Macro F1 Score": "Macro_F1",
        "Model Name": "Model_Name"
    })
    
    # Add dummy size if not in CSV (for visualization demo)
    if "Model Size (MB)" not in df.columns:
         df["Model_Size_MB"] = [260, 260, 1100, 130] # Rough estimates for A, B, C, D
         
    return df

# ----------------------------------------------------
# ACADEMIC PARETO CHART
# ----------------------------------------------------
def plot_pareto_with_indicator(df):
    plt.style.use("seaborn-v0_8-whitegrid")
    fig, ax = plt.subplots(figsize=(10, 6), dpi=100)
    
    # Data prep
    df_plot = df.sort_values("Latency_ms")
    x = df_plot["Latency_ms"].values
    y = df_plot["Macro_F1"].values

    # Axes
    ax.set_xlabel("Inference Latency (ms) [Lower is Better]", fontsize=11, fontweight='bold')
    ax.set_ylabel("F1 Score [Higher is Better]", fontsize=11, fontweight='bold')
    ax.set_title("Latency-Accuracy Pareto Frontier", fontsize=14, fontweight='bold', pad=15)

    # Zones
    ax.axvspan(0, 20, color="#d4edda", alpha=0.4)
    ax.text(10, min(y), "Real-Time Zone\n(<20ms)", ha='center', fontsize=9, color="#155724")

    # Plot Points
    for _, row in df_plot.iterrows():
        is_optimized = "Optimized" in row["Model_Name"]
        color = "#2ecc71" if is_optimized else "#34495e"
        size = 200 if is_optimized else 100
        alpha = 1.0 if row["Pareto_Optimal"] else 0.5
        marker = 'D' if is_optimized else 'o'

        ax.scatter(row["Latency_ms"], row["Macro_F1"], s=size, color=color, alpha=alpha, edgecolors="white", marker=marker, zorder=5)
        
        # Annotation
        ax.annotate(
            row["Model ID"], 
            (row["Latency_ms"], row["Macro_F1"]),
            xytext=(0, 10), textcoords='offset points',
            ha='center', fontsize=9, fontweight='bold'
        )

    # Grid
    ax.grid(True, linestyle='--', alpha=0.6)
    st.pyplot(fig)

# ----------------------------------------------------
# TRAINING SIMULATION RENDERER
# ----------------------------------------------------
def render_training_simulation():
    st.header("Training Architecture & Lifecycle Simulation")
    st.caption("Visualizing the parallel progression from raw Taglish data to Optimized ONNX graphs.")
    
    if st.button("▶ INITIATE PIPELINE SIMULATION"):
        cols = st.columns(4)
        placeholders = [cols[i].empty() for i in range(4)]
        
        epochs = 10
        raw_samples = ["Ang ganda nito!", "Sira ang item.", "Mabilis delivery.", "Recommend ko to."]
        
        for step in range(epochs + 1):
            progress = step / epochs
            
            for i, (key, meta) in enumerate(MODELS.items()):
                # Simulation math
                base_loss = max(0.1, 0.9 - (0.8 * progress))
                base_acc = 0.5 + (0.45 * progress)
                
                # Model nuances
                if key == "Model C": base_acc += 0.03 
                if key in ["Model B", "Model D"]: base_loss *= 0.8 # DAPT effect
                
                with placeholders[i].container():
                    st.markdown(f"#### {key}")
                    st.caption(meta['name'])
                    
                    # STAGE 1: Data
                    s1_active = progress < 0.2
                    s1_cls = "active-stage" if s1_active else "completed-stage"
                    txt = raw_samples[step % 4]
                    
                    st.markdown(f"""
                    <div class='training-box {s1_cls}'>
                        <p class='stage-label'>Stage 1: Pre-process</p>
                        <div class='data-preview'>{txt}</div>
                    """, unsafe_allow_html=True)
                    
                    # STAGE 2: Training
                    s2_active = 0.2 <= progress < 0.8
                    s2_cls = "active-stage" if s2_active else ("completed-stage" if progress >= 0.8 else "")
                    status = "DAPT ACTIVE" if key in ["Model B", "Model D"] else "Standard Train"
                    
                    st.markdown(f"""
                    <div style='margin-top:10px; border-top:1px solid #333; padding-top:5px;'>
                        <p class='stage-label'>Stage 2: Training</p>
                        <span style='font-size:10px; color:#aaa;'>{status}</span>
                        <div style='display:flex; justify-content:space-between; font-size:12px; margin-top:5px;'>
                            <span>Loss: <b>{base_loss:.3f}</b></span>
                            <span>Acc: <b>{base_acc:.2f}</b></span>
                        </div>
                        <progress value='{progress}' max='1' style='width:100%; height:5px;'></progress>
                    </div>
                    """, unsafe_allow_html=True)
                    
                    # STAGE 3: Opt
                    s3_active = progress >= 0.8
                    s3_cls = "active-stage" if s3_active and key == "Model D" else ""
                    opt_status = "Quantizing..." if s3_active and key == "Model D" else ("Native" if progress >= 0.8 else "Pending")
                    
                    st.markdown(f"""
                    <div style='margin-top:10px; border-top:1px solid #333; padding-top:5px;' class='{s3_cls}'>
                        <p class='stage-label'>Stage 3: Optimization</p>
                        <span style='font-size:11px; color:#fff;'>{opt_status}</span>
                    </div>
                    </div>
                    """, unsafe_allow_html=True)
            
            time.sleep(0.5)

# ----------------------------------------------------
# MAIN APP LOGIC
# ----------------------------------------------------
with st.sidebar:
    st.header("System Controls")
    mode = st.radio("Select View", ["Research Dashboard", "Live Benchmark", "Training Architecture", "Pipeline Inspector"])
    st.divider()
    st.info(f"**System Info:**\n{platform.processor()}\n\n**Acceleration:**\nCPU ONLY (Enforced)")

st.title("Thesis Simulation Platform")

if mode == "Research Dashboard":
    st.header("Optimized-DAPT DistilBERT Evaluation")
    
    df_static = load_thesis_metrics()
    if df_static is None:
        st.error("Metrics file not found. Please run '08_evaluate_metrics.py' first.")
    else:
        df_static = compute_research_metrics(df_static)
        
        # Find Model D (Optimized)
        try:
            proposed = df_static.loc[df_static["Model_Name"].str.contains("Optimized", case=False)].iloc[0]
            
            # Key Metrics Row
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Macro F1", f"{proposed['Macro_F1']:.4f}")
            c2.metric("Latency", f"{proposed['Latency_ms']:.2f} ms")
            c3.metric("Speedup Factor", f"{proposed['Speedup_Factor']:.1f}x")
            c4.metric("Performance Retained", f"{proposed['Performance_Retention']:.1f}%")
            
            st.divider()
            
            # Charts
            c_left, c_right = st.columns([2, 1])
            with c_left:
                st.subheader("Pareto Efficiency Frontier")
                plot_pareto_with_indicator(df_static)
            with c_right:
                st.subheader("Raw Metrics Data")
                st.dataframe(df_static[["Model ID", "Latency_ms", "Macro_F1", "Speedup_Factor"]], hide_index=True)
                
        except IndexError:
            st.warning("Could not find 'Optimized' model in metrics. Check your CSV data.")

elif mode == "Training Architecture":
    render_training_simulation()

elif mode == "Live Benchmark":
    st.header("Real-Time Inference Benchmark")
    text_input = st.text_area("Input Taglish Text", "Ang ganda ng quality, sulit na sulit ang bayad! Mabilis pa shipping.")
    
    if st.button("RUN BENCHMARK"):
        # 1. Visualization of Tokenization
        st.subheader("1. Tokenization Pipeline")
        tokenizer, _, _ = load_one_model("Model D") # Use Model D tokenizer as reference
        if tokenizer:
            tokens = tokenizer.tokenize(text_input)
            token_ids = tokenizer.convert_tokens_to_ids(tokens)
            
            # Display Tokens
            html_tokens = ""
            for t, tid in zip(tokens, token_ids):
                html_tokens += f"""
                <div style='display:inline-block; margin:2px; padding:5px; background:#333; border-radius:4px; text-align:center;'>
                    <span style='color:#4CAF50; font-size:12px;'>{t}</span><br>
                    <span style='color:#888; font-size:10px;'>{tid}</span>
                </div>
                """
            st.markdown(html_tokens, unsafe_allow_html=True)
        
        # 2. Inference Loop
        st.subheader("2. Inference Execution")
        results_data = []
        progress_bar = st.progress(0)
        
        for idx, (key, conf) in enumerate(MODELS.items()):
            tokenizer, model, engine = load_one_model(key)
            
            if model is None:
                results_data.append({"Model": key, "Status": "Load Failed"})
                continue
                
            # Helper for inference
            def run_inference(txt):
                if engine == "onnx":
                    inputs = tokenizer(txt, return_tensors="np", padding=True, truncation=True, max_length=128)
                    inputs = {k: v.astype(np.int64) for k, v in inputs.items()}
                    start = time.perf_counter()
                    logits = model.run(None, inputs)[0][0]
                    dur = (time.perf_counter() - start) * 1000
                    return logits, dur
                else:
                    inputs = tokenizer(txt, return_tensors="pt", padding=True, truncation=True, max_length=128)
                    
                    # --- FIX: Sanitation & CPU Force ---
                    if "token_type_ids" in inputs and ("distilbert" in conf["name"].lower() or "model_a" in key.lower() or "model_b" in key.lower()):
                         del inputs["token_type_ids"]
                    
                    # Force inputs to CPU
                    inputs = {k: v.to("cpu") for k, v in inputs.items()}

                    start = time.perf_counter()
                    with torch.no_grad():
                        logits = model(**inputs).logits[0].numpy()
                    dur = (time.perf_counter() - start) * 1000
                    return logits, dur

            # Warmup
            try:
                run_inference("warmup")
            except:
                pass # Skip warmup errors
            
            # Benchmark Run
            latencies = []
            final_logits = None
            
            for _ in range(20): # 20 iterations
                logits, dur = run_inference(text_input)
                latencies.append(dur)
                final_logits = logits
                
            # Process Result
            avg_lat = np.mean(latencies)
            probs = softmax(final_logits)
            pred_idx = np.argmax(probs)
            labels = ["Negative", "Neutral", "Positive"]
            
            results_data.append({
                "Model": key,
                "Engine": engine.upper(),
                "Avg Latency": f"{avg_lat:.2f} ms",
                "Prediction": labels[pred_idx],
                "Confidence": f"{probs[pred_idx]*100:.1f}%"
            })
            
            progress_bar.progress((idx + 1) / 4)
            
        st.table(pd.DataFrame(results_data))

elif mode == "Pipeline Inspector":
    st.header("Deep Dive Inspector")
    selected_model = st.selectbox("Select Model to Inspect", list(MODELS.keys()), index=3)
    text = st.text_input("Test Sentence", "Hindi maganda ang packaging, sira ang box.")
    
    if st.button("INSPECT TENSORS"):
        tokenizer, model, engine = load_one_model(selected_model)
        
        if tokenizer and model:
            c1, c2 = st.columns(2)
            
            with c1:
                st.markdown("### Input Features")
                inputs = tokenizer(text, return_tensors="pt" if engine == "pytorch" else "np")
                st.code(str(inputs))
                
            with c2:
                st.markdown("### Output Logits")
                if engine == "onnx":
                    in_onnx = {k: v.astype(np.int64) for k, v in inputs.items()}
                    logits = model.run(None, in_onnx)[0][0]
                else:
                    inputs_pt = tokenizer(text, return_tensors="pt")
                    # --- FIX: Sanitation & CPU Force ---
                    if "token_type_ids" in inputs_pt and "distilbert" in str(type(model)).lower():
                        del inputs_pt["token_type_ids"]
                    
                    # Force inputs to CPU
                    inputs_pt = {k: v.to("cpu") for k, v in inputs_pt.items()}

                    with torch.no_grad():
                        logits = model(**inputs_pt).logits[0].numpy()
                
                st.code(str(logits))
                
                # Viz probs
                probs = softmax(logits)
                chart_data = pd.DataFrame(probs, index=["Negative", "Neutral", "Positive"], columns=["Probability"])
                st.bar_chart(chart_data)